### ISSUE TITLE
Enable PHP 8.3 Support

### ISSUE THREAD

**Issue by AlexanderWillner** [phpro/soap-client#490] opened 2023-11-21 23:58 UTC
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

PHP 8.3 [will be released on 23rd of November 2023](https://wiki.php.net/todo/php83). Currently, the `composer.json` does not include PHP 8.3. However, the tests seem to work fine:

```shell
% php -version ; ./vendor/bin/phpunit --bootstrap test/bootstrap.php test
PHP 8.3.0-dev (cli) (built: Nov  6 2023 18:46:57) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.0-dev, Copyright (c), by Zend Technologies
PHPUnit 9.6.13 by Sebastian Bergmann and contributors.

...............................................................  63 / 205 ( 30%)
............................................................... 126 / 205 ( 61%)
............................................................... 189 / 205 ( 92%)
................                                                205 / 205 (100%)

Time: 00:00.617, Memory: 16.00 MB
```

**Comment by veewee** [comment] 2023-11-22 06:30
duplicate of #491

**Closed as completed by veewee** 2023-11-22 06:30 UTC
