### ISSUE TITLE
Support laminas/laminas-code:^4.8.0

### ISSUE THREAD

**Issue by lkck24** [phpro/soap-client#475] opened 2023-06-07 06:47 UTC
### Feature Request

Currently laminas/laminas-code is pinned to the exact version 4.8.0.

Is there a specific reason why ^4.8.0 is not allowed? So we could also use a newer version of laminas/laminas-code.

**Comment by veewee** [comment] 2023-06-07 06:50
Duplicate of https://github.com/phpro/soap-client/issues/462
This is currently fixed for v3. Feel free to provide a PR for v2.

**Closed** 2023-06-07 07:21 UTC
