### ISSUE TITLE
Phpro\SoapClient\CodeGenerator\Model\Property::getType never returns an array of type

### ISSUE THREAD

**Issue by pavlo-nahorniak** [phpro/soap-client#283] opened 2020-02-28 10:33 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version       | 1.1.2

#### Summary
Phpro\SoapClient\CodeGenerator\Model\Property::getType never return an array of type

#### Current behavior
In DTOs I would like to see a type hint with arrays of type like `@var MyType[]` but the method that returns a type always trims the `[]` at the end of type name. Currently always returns `@var MyType`. Also I didn`t find any tests that covers array behavior.

#### Expected behavior
`@var MyType[]` should be returned in a case of array

**Comment by drupol** [comment] 2020-06-05 08:38
Hello, is it related to #231 ?

**Comment by veewee** [comment] 2020-06-12 14:21
Duplicate of #231. Closing this one.

**Closed by veewee** 2020-06-12 14:21 UTC
