### ISSUE TITLE
Response object is not populated correctly

### ISSUE THREAD

**Issue by KDederichs** [phpro/soap-client#523] opened 2024-06-10 10:13 UTC
### Bug Report

I'm facing an issue where fields in the Response object are not populated correctly.

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.3.0

#### Current behavior

I have DTO's that have been generated as followed:
```php
<?php
class InfopoolEntry extends Statusmeldung
{
    /**
     * @var null | string
     */
    private ?string $id = null;

    /**
     * @var null | string
     */
    private ?string $leistungserbringerIk = null;

    /**
     * @var null | string
     */
    private ?string $kennzeichen = null;

    /**
     * @var null | \DateTimeInterface
     */
    private ?\DateTimeInterface $angelegt = null;

    /**
     * @return null | string
     */
    public function getId() : ?string
    {
        return $this->id;
    }

    /**
     * @param null | string $id
     * @return static
     */
    public function withId(?string $id) : static
    {
        $new = clone $this;
        $new->id = $id;

        return $new;
    }

    /**
     * @return null | string
     */
    public function getLeistungserbringerIk() : ?string
    {
        return $this->leistungserbringerIk;
    }

    /**
     * @param null | string $leistungserbringerIk
     * @return static
     */
    public function withLeistungserbringerIk(?string $leistungserbringerIk) : static
    {
        $new = clone $this;
        $new->leistungserbringerIk = $leistungserbringerIk;

        return $new;
    }

    /**
     * @return null | string
     */
    public function getKennzeichen() : ?string
    {
        return $this->kennzeichen;
    }

    /**
     * @param null | string $kennzeichen
     * @return static
     */
    public function withKennzeichen(?string $kennzeichen) : static
    {
        $new = clone $this;
        $new->kennzeichen = $kennzeichen;

        return $new;
    }

    /**
     * @return null | \DateTimeInterface
     */
    public function getAngelegt() : ?\DateTimeInterface
    {
        return $this->angelegt;
    }

    /**
     * @param null | \DateTimeInterface $angelegt
     * @return static
     */
    public function withAngelegt(?\DateTimeInterface $angelegt) : static
    {
        $new = clone $this;
        $new->angelegt = $angelegt;

        return $new;
    }
}
```

```php
class Statusmeldung
{
    /**
     * @var null | string
     */
    private ?string $code = null;

    /**
     * Eindeutige Kostenvoranschlagsnummer, die durch azh KVCheck vergeben wird.
     *
     * @var null | string
     */
    private ?string $kvnr_azh = null;

    /**
     * Eindeutige Kostenvoranschlagsnummer, die durch den Leistungserbringer
     * vergeben wird.
     *
     * Kann leer sein, wenn der Leistungserbringer den KV noch nicht kennt (Versorgungsanfrage, Direktauftrag).
     *
     * @var null | string
     */
    private ?string $kvnr_bsw = null;

    /**
     * @var null | string
     */
    private ?string $message = null;

    /**
     * @return null | string
     */
    public function getCode() : ?string
    {
        return $this->code;
    }

    /**
     * @param null | string $code
     * @return static
     */
    public function withCode(?string $code) : static
    {
        $new = clone $this;
        $new->code = $code;

        return $new;
    }

    /**
     * @return null | string
     */
    public function getKvnrAzh() : ?string
    {
        return $this->kvnr_azh;
    }

    /**
     * @param null | string $kvnr_azh
     * @return static
     */
    public function withKvnrAzh(?string $kvnr_azh) : static
    {
        $new = clone $this;
        $new->kvnr_azh = $kvnr_azh;

        return $new;
    }

    /**
     * @return null | string
     */
    public function getKvnrBsw() : ?string
    {
        return $this->kvnr_bsw;
    }

    /**
     * @param null | string $kvnr_bsw
     * @return static
     */
    public function withKvnrBsw(?string $kvnr_bsw) : static
    {
        $new = clone $this;
        $new->kvnr_bsw = $kvnr_bsw;

        return $new;
    }

    /**
     * @return null | string
     */
    public function getMessage() : ?string
    {
        return $this->message;
    }

    /**
     * @param null | string $message
     * @return static
     */
    public function withMessage(?string $message) : static
    {
        $new = clone $this;
        $new->message = $message;

        return $new;
    }
}
```
```php
class CheckInfopoolResponse implements ResultInterface
{
    /**
     * @var null | array<int<0,max>, \App\Azh\Type\InfopoolEntry>
     */
    private ?array $infopoolEntries = null;

    /**
     * @return null | array<int<0,max>, \App\Azh\Type\InfopoolEntry>
     */
    public function getInfopoolEntries() : ?array
    {
        return $this->infopoolEntries;
    }

    /**
     * @param null | array<int<0,max>, \App\Azh\Type\InfopoolEntry> $infopoolEntries
     * @return static
     */
    public function withInfopoolEntries(?array $infopoolEntries) : static
    {
        $new = clone $this;
        $new->infopoolEntries = $infopoolEntries;

        return $new;
    }
}
```

and a SOAP answer:
```xml
<?xml version='1.0' encoding='utf-8'?>
<soapenv:Envelope
	xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">
	<soapenv:Body>
		<ns4:checkInfopoolResponse
			xmlns:ns4="http://ws.bswsnt.vsa">
			<ns4:infopoolEntries
				xmlns:ns2="http://infopool.ws.bswsnt.vsa/xsd"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ns2:InfopoolEntry">
				<s71:kvnr_azh
					xmlns:s71="http://ws.bswsnt.vsa/xsd">8000359014
				</s71:kvnr_azh>
				<s72:kvnr_bsw
					xmlns:s72="http://ws.bswsnt.vsa/xsd">1CBevGHTtjPxiboThGLdK9
				</s72:kvnr_bsw>
				<ns2:id>8000002242459</ns2:id>
				<ns2:leistungserbringerIk>330000077</ns2:leistungserbringerIk>
				<ns2:kennzeichen>5</ns2:kennzeichen>
				<ns2:angelegt>2024-06-06T17:12:54.732+02:00</ns2:angelegt>
			</ns4:infopoolEntries>
			<ns4:infopoolEntries
				xmlns:ns2="http://infopool.ws.bswsnt.vsa/xsd"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ns2:InfopoolEntry">
				<s73:kvnr_azh
					xmlns:s73="http://ws.bswsnt.vsa/xsd">8000359013
				</s73:kvnr_azh>
				<s74:kvnr_bsw
					xmlns:s74="http://ws.bswsnt.vsa/xsd">1CBevGCZE9cS1EF6qttHLV
				</s74:kvnr_bsw>
				<ns2:id>8000002242475</ns2:id>
				<ns2:leistungserbringerIk>330000077</ns2:leistungserbringerIk>
				<ns2:kennzeichen>5</ns2:kennzeichen>
				<ns2:angelegt>2024-06-06T17:13:26.412+02:00</ns2:angelegt>
			</ns4:infopoolEntries>
			<ns4:infopoolEntries
				xmlns:ns2="http://infopool.ws.bswsnt.vsa/xsd"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ns2:InfopoolEntry">
				<s75:kvnr_azh
					xmlns:s75="http://ws.bswsnt.vsa/xsd">8000360004
				</s75:kvnr_azh>
				<s76:kvnr_bsw
					xmlns:s76="http://ws.bswsnt.vsa/xsd">1CBtPKzSWK14km67iBdZaW
				</s76:kvnr_bsw>
				<ns2:id>8000002242492</ns2:id>
				<ns2:leistungserbringerIk>330000077</ns2:leistungserbringerIk>
				<ns2:kennzeichen>5</ns2:kennzeichen>
				<ns2:angelegt>2024-06-06T17:14:07.978+02:00</ns2:angelegt>
			</ns4:infopoolEntries>
			<ns4:infopoolEntries
				xmlns:ns2="http://infopool.ws.bswsnt.vsa/xsd"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ns2:InfopoolEntry">
				<s77:kvnr_azh
					xmlns:s77="http://ws.bswsnt.vsa/xsd">8000360002
				</s77:kvnr_azh>
				<s78:kvnr_bsw
					xmlns:s78="http://ws.bswsnt.vsa/xsd">1CBswgTAdx5rEP2yFAPQJd
				</s78:kvnr_bsw>
				<ns2:id>8000002242437</ns2:id>
				<ns2:leistungserbringerIk>330000077</ns2:leistungserbringerIk>
				<ns2:kennzeichen>5</ns2:kennzeichen>
				<ns2:angelegt>2024-06-06T17:12:02.795+02:00</ns2:angelegt>
			</ns4:infopoolEntries>
			<ns4:infopoolEntries
				xmlns:ns2="http://infopool.ws.bswsnt.vsa/xsd"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ns2:InfopoolEntry">
				<s79:kvnr_azh
					xmlns:s79="http://ws.bswsnt.vsa/xsd">8000359010
				</s79:kvnr_azh>
				<s80:kvnr_bsw
					xmlns:s80="http://ws.bswsnt.vsa/xsd">1CBeudgh7TWoqsyVQq8TPL
				</s80:kvnr_bsw>
				<ns2:id>8000002242510</ns2:id>
				<ns2:leistungserbringerIk>330000077</ns2:leistungserbringerIk>
				<ns2:kennzeichen>5</ns2:kennzeichen>
				<ns2:angelegt>2024-06-06T17:15:18.534+02:00</ns2:angelegt>
			</ns4:infopoolEntries>
		</ns4:checkInfopoolResponse>
	</soapenv:Body>
</soapenv:Envelope>
```

When iterating through the `InfoPoolEntry` objects and calling `getKvnrAzh` or 'getKvnrBsw' they will always return null, despite being clearly present in the answer.
When dumping the object with the Symfony `dd` command you'll get this:
<img width="464" alt="Screenshot 2024-06-10 at 12 09 56" src="https://github.com/phpro/soap-client/assets/24696606/0917a65e-7683-488a-a79d-5949e72a13d7">

As you can see the existing object properties are null and it adds `"kvnr_azh"` and `"kvnr_bsw"` as new properties to the object, adding them as new property instead of populating the existing ones for some reason.

#### How to reproduce

I think it's related to the naming of the fields since it's only the ones with a "_" in the name have that issue, so I guess try a SOAP service that returns an answer with those.

#### Expected behavior

It should fill out the existing properties instead of adding new ones.

**Comment by veewee** [comment] 2024-06-10 10:23
Hello,

It are the properties that are inherited which are marked as private.
You can generate them as `protected`instead.

More info:
- https://github.com/phpro/soap-client/issues/513
- https://github.com/veewee/reflecta/issues/5

**Comment by KDederichs** [comment] 2024-06-10 10:38
That did the trick, thanks!
Wouldn't it be maybe better then to default to protected property generation? Since I'm clearly not the only one running into that issue

**Comment by veewee** [comment] 2024-06-10 11:20
That could be a solution.

However, the problem is not the visibility but rather php's ext-soap encoding that cannot hydrate the object sufficiently 
I could overcome this issue with the new encoding system.

Not sure if it's worth fixing if switching to protected properties just work.

**Comment by KDederichs** [comment] 2024-06-10 11:24
Yeah it's by no means a perfect solution but it would be a good stopgap till something proper is in place. (Or maybe it's just good enough)

**Comment by veewee** [comment] 2024-06-11 08:20
Closing this one for now. It's on my radar for v4.
https://github.com/phpro/soap-client/issues/485

**Closed as completed by veewee** 2024-06-11 08:20 UTC

**Comment by veewee** [comment] 2024-06-12 07:54
FYI : I've applied a fix in reflecta (which will be used in v4 for hydrating)
https://github.com/veewee/reflecta/pull/12

This should be fixed in v4, so I don't think there is a need for marking it as protected by default anymore.

**Comment by KDederichs** [comment] 2024-06-12 10:22
Ok, sounds good to me, thanks :D

**Comment by veewee** [comment] 2024-07-05 09:31
Hello there @KDederichs ,

I wanted to get back to this issue:
We are finishing up v4 of the soap-client package which uses a new encoding system internally.
With this new system, you should be able to get around this issue more easily.

We are eager to receive some early feedback on this new release.
If you got some time, feel free to play around with the alpha version:


* Release: https://github.com/phpro/soap-client/releases/tag/4.0.0-alpha1
* Discussion: https://github.com/phpro/soap-client/discussions/527
