### ISSUE TITLE
Using IteratorAggregate doesnt have an effect on array type

### ISSUE THREAD

**Issue by jariesdev** [phpro/soap-client#271] opened 2020-01-10 08:20 UTC
### Bug Report

I have a Request with an array of **RequestedPackages** but when I try to store array of types on a property it doesn't work at all even though I implement IteratorAggregate interface.

Request: $requestedPackages should be array

```
$requestedPackages = [];
 $dimension = (new DocTypeRefDimensionsType)
                ->withLength(1)
                ->withWidth(1)
                ->withHeight(1);
$requestedPackages[] = (new DocTypeRefRequestedPackagesType)
                ->withWeight(2)
                ->withDimensions($dimension)
                ->withNumber(1);
$packages = (new DocTypeRefPackagesType)
            ->withRequestedPackages($requestedPackages);

 $dimension = (new DocTypeRefDimensionsType)
                ->withLength(2)
                ->withWidth(2)
                ->withHeight(2);
$requestedPackages[] = (new DocTypeRefRequestedPackagesType)
                ->withWeight(1)
                ->withDimensions($dimension)
                ->withNumber(2);
$packages = (new DocTypeRefPackagesType)
            ->withRequestedPackages($requestedPackages);
```
Error Exception Occur: SOAP-ERROR: Encoding: object has no 'Weight' property

I suspect that the **RequestedPackages** was tried to access its property directly (Weight) and not iterating over the array element beforehand.

Expected Behavior to generate this XML:
```
<Packages>
               <RequestedPackages number="1">
                  <Weight>2</Weight>
                  <Dimensions>
                     <!--You may enter the following 3 items in any order-->
                     <Length>1</Length>
                     <Width>1</Width>
                     <Height>1</Height>
                  </Dimensions>
             </RequestedPackages>

<RequestedPackages number="2">
                  <Weight>1</Weight>
                  <Dimensions>
                     <!--You may enter the following 3 items in any order-->
                     <Length>2</Length>
                     <Width>2</Width>
                     <Height>2</Height>
                  </Dimensions>
               </RequestedPackages>
            </Packages>
```

DocTypeRefRequestedPackagesType
```
use IteratorAggregate;

class DocTypeRefPackagesType implements IteratorAggregate
{

    private $RequestedPackages;

    public function getIterator(): array
    {
        return new \ArrayIterator(is_array($this->RequestedPackages) ? $this->RequestedPackages : []);
    }

    public function getRequestedPackages(): array
    {
        return $this->RequestedPackages;
    }
}

```

WSDL Type:
```
<xsd:complexType name="docTypeRef_PackagesType">
<xsd:sequence maxOccurs="999">
<xsd:element name="RequestedPackages" type="tns:docTypeRef_RequestedPackagesType"/>
</xsd:sequence>
</xsd:complexType>
```

Btw, thank you for this library. Its great!

**Comment by veewee** [comment] 2020-06-12 14:26
Thanks for reporting, closing it since it is a duplicate of #231

**Closed by veewee** 2020-06-12 14:26 UTC
