### ISSUE TITLE
Long namespace in type hints

### ISSUE THREAD

**Issue by WinterSilence** [phpro/soap-client#278] opened 2020-02-10 00:39 UTC
### Bug Report
short namespace:
RequestInterface|`WsdlType`\SendClaimRequestMsg
long namespace in type hints
sendClaim(`\Rkn\WsdlType`\SendClaimRequestMsg $parameters) : `\Rkn\WsdlType`\SendClaimResponseMsg
~~~
namespace Rkn;
use Rkn\WsdlType;
use Phpro\SoapClient\Type\RequestInterface;
use Phpro\SoapClient\Type\ResultInterface;
use Phpro\SoapClient\Client;
class WsdlClient extends Client {
    /**
     * @param RequestInterface|WsdlType\SendClaimRequestMsg $parameters
     * @return ResultInterface|WsdlType\SendClaimResponseMsg
     */
    public function sendClaim(\Rkn\WsdlType\SendClaimRequestMsg $parameters) : \Rkn\WsdlType\SendClaimResponseMsg
    {
        return $this->call('sendClaim', $parameters);
    }
}
~~~

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.1.2

**Comment by drupol** [comment] 2020-06-05 08:36
Hello,

Do you mind elaborating a bit more ?

**Comment by WinterSilence** [comment] 2020-06-05 09:17
@drupol I look to #281 - it's a waste of my time

**Comment by drupol** [comment] 2020-06-05 09:44
If the issue is out of date, could you please close it ?

**Comment by veewee** [comment] 2020-06-12 14:18
The long namespaces are the way laminas-code work. We cannot change that in this repo.
However, there is a php-cs-fixer that can do that for you after code generation:

Option: `fully_qualified_strict_types`
https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Closed by veewee** 2020-06-12 14:18 UTC
